### PR TITLE
Add commission and slippage on premium and annual to the quote route

### PR DESCRIPTION
**Pull request by MilGard91**
## Context

Issue: #60 #61  

## Changes proposed in this pull request

- a helper function to add commission and slippage to the passed value
- utilize helper to calculate premium and annual price with commission and slippage

## Test plan

- Added unit test for the quote route that uses commission and slippage

## Checklist

- [x] Rebased the base branch
- [x] Attached corresponding Github issue
- [x] Prefixed the name with the type of change (i.e. feat, chore, test)
- [x] Performed a self-review of my own code
- [x] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [x] Didn't generate new warnings
- [x] Didn't generate failures on existing tests
- [x] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

### CODE REVIEW

**Review by mixplore — APPROVED** [review]
🚀 Looks great!

**Comment by shark0der** [comment]
This doesn't feel like the proper place for the slippage and commission calculation but we agreed to merge it and revisit this later. One of the issues with the code right now is the presence of business logic inside the controller - controllers should be skinny as they're not reusable and testing is weirder. Same applies for `annualPrice` which is calculated in the controller as well. A proper place for the commission and slippage would be inside the sdk. The annual price on the other hand should probably be inside the quote engine itself.

**Comment by MilGard91** [comment]
LGTM

**Comment by shark0der** [comment]
Won't merge as we decided to move this to the SDK.

**Pull request closed without merging**
